//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNBSoap.MnbServicereference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrenciesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrenciesResult {
            get {
                return this.GetCurrenciesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrenciesResultField, value) != true)) {
                    this.GetCurrenciesResultField = value;
                    this.RaisePropertyChanged("GetCurrenciesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrencyUnitsResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrencyUnitsResult {
            get {
                return this.GetCurrencyUnitsResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrencyUnitsResultField, value) != true)) {
                    this.GetCurrencyUnitsResultField = value;
                    this.RaisePropertyChanged("GetCurrencyUnitsResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrentExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrentExchangeRatesResult {
            get {
                return this.GetCurrentExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrentExchangeRatesResultField, value) != true)) {
                    this.GetCurrentExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetCurrentExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetDateIntervalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetDateIntervalResult {
            get {
                return this.GetDateIntervalResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetDateIntervalResultField, value) != true)) {
                    this.GetDateIntervalResultField = value;
                    this.RaisePropertyChanged("GetDateIntervalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((object.ReferenceEquals(this.startDateField, value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((object.ReferenceEquals(this.endDateField, value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetExchangeRatesResult {
            get {
                return this.GetExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetExchangeRatesResultField, value) != true)) {
                    this.GetExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetInfoResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetInfoResult {
            get {
                return this.GetInfoResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetInfoResultField, value) != true)) {
                    this.GetInfoResultField = value;
                    this.RaisePropertyChanged("GetInfoResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="MnbServicereference.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetCurrencies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MNBSoap.MnbServicereference.GetCurrenciesResponse GetCurrencies(MNBSoap.MnbServicereference.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrenciesResponse> GetCurrenciesAsync(MNBSoap.MnbServicereference.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrencyUnits is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MNBSoap.MnbServicereference.GetCurrencyUnitsResponse GetCurrencyUnits(MNBSoap.MnbServicereference.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(MNBSoap.MnbServicereference.GetCurrencyUnitsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrentExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStrin" +
            "gFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDateInterval is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MNBSoap.MnbServicereference.GetDateIntervalResponse GetDateInterval(MNBSoap.MnbServicereference.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetDateIntervalResponse> GetDateIntervalAsync(MNBSoap.MnbServicereference.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since the operation GetExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MNBSoap.MnbServicereference.GetExchangeRatesResponse GetExchangeRates(MNBSoap.MnbServicereference.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetExchangeRatesResponse> GetExchangeRatesAsync(MNBSoap.MnbServicereference.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        MNBSoap.MnbServicereference.GetInfoResponse GetInfo(MNBSoap.MnbServicereference.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetInfoResponse> GetInfoAsync(MNBSoap.MnbServicereference.GetInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetCurrenciesRequestBody GetCurrencies;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(MNBSoap.MnbServicereference.GetCurrenciesRequestBody GetCurrencies) {
            this.GetCurrencies = GetCurrencies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetCurrenciesResponseBody GetCurrenciesResponse1;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(MNBSoap.MnbServicereference.GetCurrenciesResponseBody GetCurrenciesResponse1) {
            this.GetCurrenciesResponse1 = GetCurrenciesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetCurrencyUnitsRequestBody GetCurrencyUnits;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(MNBSoap.MnbServicereference.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            this.GetCurrencyUnits = GetCurrencyUnits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(MNBSoap.MnbServicereference.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1) {
            this.GetCurrencyUnitsResponse1 = GetCurrencyUnitsResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            this.GetCurrentExchangeRates = GetCurrentExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1) {
            this.GetCurrentExchangeRatesResponse1 = GetCurrentExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetDateIntervalRequestBody GetDateInterval;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(MNBSoap.MnbServicereference.GetDateIntervalRequestBody GetDateInterval) {
            this.GetDateInterval = GetDateInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetDateIntervalResponseBody GetDateIntervalResponse1;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(MNBSoap.MnbServicereference.GetDateIntervalResponseBody GetDateIntervalResponse1) {
            this.GetDateIntervalResponse1 = GetDateIntervalResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetExchangeRatesRequestBody GetExchangeRates;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(MNBSoap.MnbServicereference.GetExchangeRatesRequestBody GetExchangeRates) {
            this.GetExchangeRates = GetExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetExchangeRatesResponseBody GetExchangeRatesResponse1;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(MNBSoap.MnbServicereference.GetExchangeRatesResponseBody GetExchangeRatesResponse1) {
            this.GetExchangeRatesResponse1 = GetExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetInfoRequestBody GetInfo;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(MNBSoap.MnbServicereference.GetInfoRequestBody GetInfo) {
            this.GetInfo = GetInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public MNBSoap.MnbServicereference.GetInfoResponseBody GetInfoResponse1;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(MNBSoap.MnbServicereference.GetInfoResponseBody GetInfoResponse1) {
            this.GetInfoResponse1 = GetInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : MNBSoap.MnbServicereference.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<MNBSoap.MnbServicereference.MNBArfolyamServiceSoap>, MNBSoap.MnbServicereference.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBSoap.MnbServicereference.GetCurrenciesResponse MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetCurrencies(MNBSoap.MnbServicereference.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public MNBSoap.MnbServicereference.GetCurrenciesResponseBody GetCurrencies(MNBSoap.MnbServicereference.GetCurrenciesRequestBody GetCurrencies1) {
            MNBSoap.MnbServicereference.GetCurrenciesRequest inValue = new MNBSoap.MnbServicereference.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies1;
            MNBSoap.MnbServicereference.GetCurrenciesResponse retVal = ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.GetCurrenciesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrenciesResponse> MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetCurrenciesAsync(MNBSoap.MnbServicereference.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrenciesResponse> GetCurrenciesAsync(MNBSoap.MnbServicereference.GetCurrenciesRequestBody GetCurrencies) {
            MNBSoap.MnbServicereference.GetCurrenciesRequest inValue = new MNBSoap.MnbServicereference.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies;
            return ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBSoap.MnbServicereference.GetCurrencyUnitsResponse MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetCurrencyUnits(MNBSoap.MnbServicereference.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public MNBSoap.MnbServicereference.GetCurrencyUnitsResponseBody GetCurrencyUnits(MNBSoap.MnbServicereference.GetCurrencyUnitsRequestBody GetCurrencyUnits1) {
            MNBSoap.MnbServicereference.GetCurrencyUnitsRequest inValue = new MNBSoap.MnbServicereference.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits1;
            MNBSoap.MnbServicereference.GetCurrencyUnitsResponse retVal = ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.GetCurrencyUnitsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrencyUnitsResponse> MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(MNBSoap.MnbServicereference.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(MNBSoap.MnbServicereference.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            MNBSoap.MnbServicereference.GetCurrencyUnitsRequest inValue = new MNBSoap.MnbServicereference.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits;
            return ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponse MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetCurrentExchangeRates(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRates(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates1) {
            MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest inValue = new MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates1;
            MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponse retVal = ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.GetCurrentExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponse> MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest inValue = new MNBSoap.MnbServicereference.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates;
            return ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBSoap.MnbServicereference.GetDateIntervalResponse MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetDateInterval(MNBSoap.MnbServicereference.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public MNBSoap.MnbServicereference.GetDateIntervalResponseBody GetDateInterval(MNBSoap.MnbServicereference.GetDateIntervalRequestBody GetDateInterval1) {
            MNBSoap.MnbServicereference.GetDateIntervalRequest inValue = new MNBSoap.MnbServicereference.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval1;
            MNBSoap.MnbServicereference.GetDateIntervalResponse retVal = ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.GetDateIntervalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetDateIntervalResponse> MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetDateIntervalAsync(MNBSoap.MnbServicereference.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetDateIntervalResponse> GetDateIntervalAsync(MNBSoap.MnbServicereference.GetDateIntervalRequestBody GetDateInterval) {
            MNBSoap.MnbServicereference.GetDateIntervalRequest inValue = new MNBSoap.MnbServicereference.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval;
            return ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBSoap.MnbServicereference.GetExchangeRatesResponse MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetExchangeRates(MNBSoap.MnbServicereference.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public MNBSoap.MnbServicereference.GetExchangeRatesResponseBody GetExchangeRates(MNBSoap.MnbServicereference.GetExchangeRatesRequestBody GetExchangeRates1) {
            MNBSoap.MnbServicereference.GetExchangeRatesRequest inValue = new MNBSoap.MnbServicereference.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates1;
            MNBSoap.MnbServicereference.GetExchangeRatesResponse retVal = ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.GetExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetExchangeRatesResponse> MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetExchangeRatesAsync(MNBSoap.MnbServicereference.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetExchangeRatesResponse> GetExchangeRatesAsync(MNBSoap.MnbServicereference.GetExchangeRatesRequestBody GetExchangeRates) {
            MNBSoap.MnbServicereference.GetExchangeRatesRequest inValue = new MNBSoap.MnbServicereference.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates;
            return ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNBSoap.MnbServicereference.GetInfoResponse MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetInfo(MNBSoap.MnbServicereference.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public MNBSoap.MnbServicereference.GetInfoResponseBody GetInfo(MNBSoap.MnbServicereference.GetInfoRequestBody GetInfo1) {
            MNBSoap.MnbServicereference.GetInfoRequest inValue = new MNBSoap.MnbServicereference.GetInfoRequest();
            inValue.GetInfo = GetInfo1;
            MNBSoap.MnbServicereference.GetInfoResponse retVal = ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.GetInfoResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetInfoResponse> MNBSoap.MnbServicereference.MNBArfolyamServiceSoap.GetInfoAsync(MNBSoap.MnbServicereference.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNBSoap.MnbServicereference.GetInfoResponse> GetInfoAsync(MNBSoap.MnbServicereference.GetInfoRequestBody GetInfo) {
            MNBSoap.MnbServicereference.GetInfoRequest inValue = new MNBSoap.MnbServicereference.GetInfoRequest();
            inValue.GetInfo = GetInfo;
            return ((MNBSoap.MnbServicereference.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
    }
}
